import Head from 'next/head'
import ChooseUs from '../components/ChooseUs'
import DellorYourTrips from '../components/DellorYourTrips'
import FAQ from '../components/FAQ'
import FeaturedArticles from '../components/FeaturedArticles'
import Footer from '../components/Footer'
import FormSearch from '../components/FormSearch'
import Galliry from '../components/Galliry'
import GroupPackage from '../components/GroupPackage'
import MainHeader from '../components/MainHeader'
import NavBar from '../components/NavBar'
import PackageContainer from '../components/PackageContainer'
import Reviews from '../components/Reviews'
// import { Alert } from "flowbite-react";

export default function Home() {
  return (
    <div className='' >
      <Head>
        <title>Travel Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <MainHeader/>
      <FormSearch/>
     
      <ChooseUs/>
       <div className='pt-11'>
          <PackageContainer/>
          <GroupPackage/>
       </div>
       <DellorYourTrips/>
       <Galliry/>
       <Reviews/>
       <FeaturedArticles/>  
       <FAQ/>
       <Footer/>
    </div>
  )
}
